#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_Proiect
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_Proiect")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAngajati(Angajati instance);
    partial void UpdateAngajati(Angajati instance);
    partial void DeleteAngajati(Angajati instance);
    partial void InsertAutor(Autor instance);
    partial void UpdateAutor(Autor instance);
    partial void DeleteAutor(Autor instance);
    partial void InsertClienti(Clienti instance);
    partial void UpdateClienti(Clienti instance);
    partial void DeleteClienti(Clienti instance);
    partial void InsertComenzi(Comenzi instance);
    partial void UpdateComenzi(Comenzi instance);
    partial void DeleteComenzi(Comenzi instance);
    partial void InsertDepartamente(Departamente instance);
    partial void UpdateDepartamente(Departamente instance);
    partial void DeleteDepartamente(Departamente instance);
    partial void InsertDepozit(Depozit instance);
    partial void UpdateDepozit(Depozit instance);
    partial void DeleteDepozit(Depozit instance);
    partial void InsertExpozitie(Expozitie instance);
    partial void UpdateExpozitie(Expozitie instance);
    partial void DeleteExpozitie(Expozitie instance);
    partial void InsertFunctii(Functii instance);
    partial void UpdateFunctii(Functii instance);
    partial void DeleteFunctii(Functii instance);
    partial void InsertOpere_De_Arta(Opere_De_Arta instance);
    partial void UpdateOpere_De_Arta(Opere_De_Arta instance);
    partial void DeleteOpere_De_Arta(Opere_De_Arta instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::BD_Proiect.Properties.Settings.Default.BD_ProiectConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Angajati> Angajatis
		{
			get
			{
				return this.GetTable<Angajati>();
			}
		}
		
		public System.Data.Linq.Table<Autor> Autors
		{
			get
			{
				return this.GetTable<Autor>();
			}
		}
		
		public System.Data.Linq.Table<Clienti> Clientis
		{
			get
			{
				return this.GetTable<Clienti>();
			}
		}
		
		public System.Data.Linq.Table<Comenzi> Comenzis
		{
			get
			{
				return this.GetTable<Comenzi>();
			}
		}
		
		public System.Data.Linq.Table<Comenzi_Opere_De_Arta> Comenzi_Opere_De_Artas
		{
			get
			{
				return this.GetTable<Comenzi_Opere_De_Arta>();
			}
		}
		
		public System.Data.Linq.Table<Departamente> Departamentes
		{
			get
			{
				return this.GetTable<Departamente>();
			}
		}
		
		public System.Data.Linq.Table<Depozit> Depozits
		{
			get
			{
				return this.GetTable<Depozit>();
			}
		}
		
		public System.Data.Linq.Table<Depozite_Opere> Depozite_Operes
		{
			get
			{
				return this.GetTable<Depozite_Opere>();
			}
		}
		
		public System.Data.Linq.Table<Expozitie> Expozities
		{
			get
			{
				return this.GetTable<Expozitie>();
			}
		}
		
		public System.Data.Linq.Table<Functii> Functiis
		{
			get
			{
				return this.GetTable<Functii>();
			}
		}
		
		public System.Data.Linq.Table<Expozitii_Opere_De_Arta> Expozitii_Opere_De_Artas
		{
			get
			{
				return this.GetTable<Expozitii_Opere_De_Arta>();
			}
		}
		
		public System.Data.Linq.Table<Functii_Angajati> Functii_Angajatis
		{
			get
			{
				return this.GetTable<Functii_Angajati>();
			}
		}
		
		public System.Data.Linq.Table<Galerii_Departamente> Galerii_Departamentes
		{
			get
			{
				return this.GetTable<Galerii_Departamente>();
			}
		}
		
		public System.Data.Linq.Table<Opere_De_Arta> Opere_De_Artas
		{
			get
			{
				return this.GetTable<Opere_De_Arta>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Angajati")]
	public partial class Angajati : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Angajat;
		
		private string _Nume;
		
		private string _Prenume;
		
		private string _CNP;
		
		private System.DateTime _Data_Nastere;
		
		private double _Salariu_Brut_;
		
		private bool _Lider;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_AngajatChanging(int value);
    partial void OnID_AngajatChanged();
    partial void OnNumeChanging(string value);
    partial void OnNumeChanged();
    partial void OnPrenumeChanging(string value);
    partial void OnPrenumeChanged();
    partial void OnCNPChanging(string value);
    partial void OnCNPChanged();
    partial void OnData_NastereChanging(System.DateTime value);
    partial void OnData_NastereChanged();
    partial void OnSalariu_Brut_Changing(double value);
    partial void OnSalariu_Brut_Changed();
    partial void OnLiderChanging(bool value);
    partial void OnLiderChanged();
    #endregion
		
		public Angajati()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Angajat", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Angajat
		{
			get
			{
				return this._ID_Angajat;
			}
			set
			{
				if ((this._ID_Angajat != value))
				{
					this.OnID_AngajatChanging(value);
					this.SendPropertyChanging();
					this._ID_Angajat = value;
					this.SendPropertyChanged("ID_Angajat");
					this.OnID_AngajatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this.OnNumeChanging(value);
					this.SendPropertyChanging();
					this._Nume = value;
					this.SendPropertyChanged("Nume");
					this.OnNumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenume", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Prenume
		{
			get
			{
				return this._Prenume;
			}
			set
			{
				if ((this._Prenume != value))
				{
					this.OnPrenumeChanging(value);
					this.SendPropertyChanging();
					this._Prenume = value;
					this.SendPropertyChanged("Prenume");
					this.OnPrenumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNP", DbType="Char(13) NOT NULL", CanBeNull=false)]
		public string CNP
		{
			get
			{
				return this._CNP;
			}
			set
			{
				if ((this._CNP != value))
				{
					this.OnCNPChanging(value);
					this.SendPropertyChanging();
					this._CNP = value;
					this.SendPropertyChanged("CNP");
					this.OnCNPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_Nastere", DbType="Date NOT NULL")]
		public System.DateTime Data_Nastere
		{
			get
			{
				return this._Data_Nastere;
			}
			set
			{
				if ((this._Data_Nastere != value))
				{
					this.OnData_NastereChanging(value);
					this.SendPropertyChanging();
					this._Data_Nastere = value;
					this.SendPropertyChanged("Data_Nastere");
					this.OnData_NastereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Salariu(Brut)]", Storage="_Salariu_Brut_", DbType="Float NOT NULL")]
		public double Salariu_Brut_
		{
			get
			{
				return this._Salariu_Brut_;
			}
			set
			{
				if ((this._Salariu_Brut_ != value))
				{
					this.OnSalariu_Brut_Changing(value);
					this.SendPropertyChanging();
					this._Salariu_Brut_ = value;
					this.SendPropertyChanged("Salariu_Brut_");
					this.OnSalariu_Brut_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lider", DbType="Bit NOT NULL")]
		public bool Lider
		{
			get
			{
				return this._Lider;
			}
			set
			{
				if ((this._Lider != value))
				{
					this.OnLiderChanging(value);
					this.SendPropertyChanging();
					this._Lider = value;
					this.SendPropertyChanged("Lider");
					this.OnLiderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Autor")]
	public partial class Autor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Autor;
		
		private string _Nume;
		
		private string _Prenume;
		
		private System.DateTime _Data_Nastere;
		
		private EntitySet<Opere_De_Arta> _Opere_De_Artas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_AutorChanging(int value);
    partial void OnID_AutorChanged();
    partial void OnNumeChanging(string value);
    partial void OnNumeChanged();
    partial void OnPrenumeChanging(string value);
    partial void OnPrenumeChanged();
    partial void OnData_NastereChanging(System.DateTime value);
    partial void OnData_NastereChanged();
    #endregion
		
		public Autor()
		{
			this._Opere_De_Artas = new EntitySet<Opere_De_Arta>(new Action<Opere_De_Arta>(this.attach_Opere_De_Artas), new Action<Opere_De_Arta>(this.detach_Opere_De_Artas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Autor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Autor
		{
			get
			{
				return this._ID_Autor;
			}
			set
			{
				if ((this._ID_Autor != value))
				{
					this.OnID_AutorChanging(value);
					this.SendPropertyChanging();
					this._ID_Autor = value;
					this.SendPropertyChanged("ID_Autor");
					this.OnID_AutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this.OnNumeChanging(value);
					this.SendPropertyChanging();
					this._Nume = value;
					this.SendPropertyChanged("Nume");
					this.OnNumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenume", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string Prenume
		{
			get
			{
				return this._Prenume;
			}
			set
			{
				if ((this._Prenume != value))
				{
					this.OnPrenumeChanging(value);
					this.SendPropertyChanging();
					this._Prenume = value;
					this.SendPropertyChanged("Prenume");
					this.OnPrenumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_Nastere", DbType="Date NOT NULL")]
		public System.DateTime Data_Nastere
		{
			get
			{
				return this._Data_Nastere;
			}
			set
			{
				if ((this._Data_Nastere != value))
				{
					this.OnData_NastereChanging(value);
					this.SendPropertyChanging();
					this._Data_Nastere = value;
					this.SendPropertyChanged("Data_Nastere");
					this.OnData_NastereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Autor_Opere_De_Arta", Storage="_Opere_De_Artas", ThisKey="ID_Autor", OtherKey="ID_Autor")]
		public EntitySet<Opere_De_Arta> Opere_De_Artas
		{
			get
			{
				return this._Opere_De_Artas;
			}
			set
			{
				this._Opere_De_Artas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Opere_De_Artas(Opere_De_Arta entity)
		{
			this.SendPropertyChanging();
			entity.Autor = this;
		}
		
		private void detach_Opere_De_Artas(Opere_De_Arta entity)
		{
			this.SendPropertyChanging();
			entity.Autor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clienti")]
	public partial class Clienti : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Client;
		
		private string _Nume;
		
		private string _Prenume;
		
		private string _Numar_Telefon;
		
		private string _Adresa;
		
		private string _Localitate;
		
		private EntitySet<Comenzi> _Comenzis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ClientChanging(int value);
    partial void OnID_ClientChanged();
    partial void OnNumeChanging(string value);
    partial void OnNumeChanged();
    partial void OnPrenumeChanging(string value);
    partial void OnPrenumeChanged();
    partial void OnNumar_TelefonChanging(string value);
    partial void OnNumar_TelefonChanged();
    partial void OnAdresaChanging(string value);
    partial void OnAdresaChanged();
    partial void OnLocalitateChanging(string value);
    partial void OnLocalitateChanged();
    #endregion
		
		public Clienti()
		{
			this._Comenzis = new EntitySet<Comenzi>(new Action<Comenzi>(this.attach_Comenzis), new Action<Comenzi>(this.detach_Comenzis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Client", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Client
		{
			get
			{
				return this._ID_Client;
			}
			set
			{
				if ((this._ID_Client != value))
				{
					this.OnID_ClientChanging(value);
					this.SendPropertyChanging();
					this._ID_Client = value;
					this.SendPropertyChanged("ID_Client");
					this.OnID_ClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this.OnNumeChanging(value);
					this.SendPropertyChanging();
					this._Nume = value;
					this.SendPropertyChanged("Nume");
					this.OnNumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenume", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string Prenume
		{
			get
			{
				return this._Prenume;
			}
			set
			{
				if ((this._Prenume != value))
				{
					this.OnPrenumeChanging(value);
					this.SendPropertyChanging();
					this._Prenume = value;
					this.SendPropertyChanged("Prenume");
					this.OnPrenumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numar_Telefon", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Numar_Telefon
		{
			get
			{
				return this._Numar_Telefon;
			}
			set
			{
				if ((this._Numar_Telefon != value))
				{
					this.OnNumar_TelefonChanging(value);
					this.SendPropertyChanging();
					this._Numar_Telefon = value;
					this.SendPropertyChanged("Numar_Telefon");
					this.OnNumar_TelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresa", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Adresa
		{
			get
			{
				return this._Adresa;
			}
			set
			{
				if ((this._Adresa != value))
				{
					this.OnAdresaChanging(value);
					this.SendPropertyChanging();
					this._Adresa = value;
					this.SendPropertyChanged("Adresa");
					this.OnAdresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Localitate", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Localitate
		{
			get
			{
				return this._Localitate;
			}
			set
			{
				if ((this._Localitate != value))
				{
					this.OnLocalitateChanging(value);
					this.SendPropertyChanging();
					this._Localitate = value;
					this.SendPropertyChanged("Localitate");
					this.OnLocalitateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Clienti_Comenzi", Storage="_Comenzis", ThisKey="ID_Client", OtherKey="ID_Client")]
		public EntitySet<Comenzi> Comenzis
		{
			get
			{
				return this._Comenzis;
			}
			set
			{
				this._Comenzis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comenzis(Comenzi entity)
		{
			this.SendPropertyChanging();
			entity.Clienti = this;
		}
		
		private void detach_Comenzis(Comenzi entity)
		{
			this.SendPropertyChanging();
			entity.Clienti = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comenzi")]
	public partial class Comenzi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Comanda;
		
		private int _ID_Client;
		
		private System.DateTime _Data_Plasare;
		
		private System.Nullable<System.DateTime> _Data_Livrare;
		
		private System.Nullable<int> _ID_User;
		
		private EntityRef<Clienti> _Clienti;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ComandaChanging(int value);
    partial void OnID_ComandaChanged();
    partial void OnID_ClientChanging(int value);
    partial void OnID_ClientChanged();
    partial void OnData_PlasareChanging(System.DateTime value);
    partial void OnData_PlasareChanged();
    partial void OnData_LivrareChanging(System.Nullable<System.DateTime> value);
    partial void OnData_LivrareChanged();
    partial void OnID_UserChanging(System.Nullable<int> value);
    partial void OnID_UserChanged();
    #endregion
		
		public Comenzi()
		{
			this._Clienti = default(EntityRef<Clienti>);
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Comanda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Comanda
		{
			get
			{
				return this._ID_Comanda;
			}
			set
			{
				if ((this._ID_Comanda != value))
				{
					this.OnID_ComandaChanging(value);
					this.SendPropertyChanging();
					this._ID_Comanda = value;
					this.SendPropertyChanged("ID_Comanda");
					this.OnID_ComandaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Client", DbType="Int NOT NULL")]
		public int ID_Client
		{
			get
			{
				return this._ID_Client;
			}
			set
			{
				if ((this._ID_Client != value))
				{
					if (this._Clienti.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ClientChanging(value);
					this.SendPropertyChanging();
					this._ID_Client = value;
					this.SendPropertyChanged("ID_Client");
					this.OnID_ClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_Plasare", DbType="Date NOT NULL")]
		public System.DateTime Data_Plasare
		{
			get
			{
				return this._Data_Plasare;
			}
			set
			{
				if ((this._Data_Plasare != value))
				{
					this.OnData_PlasareChanging(value);
					this.SendPropertyChanging();
					this._Data_Plasare = value;
					this.SendPropertyChanged("Data_Plasare");
					this.OnData_PlasareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_Livrare", DbType="Date")]
		public System.Nullable<System.DateTime> Data_Livrare
		{
			get
			{
				return this._Data_Livrare;
			}
			set
			{
				if ((this._Data_Livrare != value))
				{
					this.OnData_LivrareChanging(value);
					this.SendPropertyChanging();
					this._Data_Livrare = value;
					this.SendPropertyChanged("Data_Livrare");
					this.OnData_LivrareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_User", DbType="Int")]
		public System.Nullable<int> ID_User
		{
			get
			{
				return this._ID_User;
			}
			set
			{
				if ((this._ID_User != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_UserChanging(value);
					this.SendPropertyChanging();
					this._ID_User = value;
					this.SendPropertyChanged("ID_User");
					this.OnID_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Clienti_Comenzi", Storage="_Clienti", ThisKey="ID_Client", OtherKey="ID_Client", IsForeignKey=true)]
		public Clienti Clienti
		{
			get
			{
				return this._Clienti.Entity;
			}
			set
			{
				Clienti previousValue = this._Clienti.Entity;
				if (((previousValue != value) 
							|| (this._Clienti.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Clienti.Entity = null;
						previousValue.Comenzis.Remove(this);
					}
					this._Clienti.Entity = value;
					if ((value != null))
					{
						value.Comenzis.Add(this);
						this._ID_Client = value.ID_Client;
					}
					else
					{
						this._ID_Client = default(int);
					}
					this.SendPropertyChanged("Clienti");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Comenzi", Storage="_User", ThisKey="ID_User", OtherKey="ID", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Comenzis.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Comenzis.Add(this);
						this._ID_User = value.ID;
					}
					else
					{
						this._ID_User = default(Nullable<int>);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comenzi_Opere_De_Arta")]
	public partial class Comenzi_Opere_De_Arta
	{
		
		private int _ID_Opera;
		
		private int _ID_Comenzi;
		
		public Comenzi_Opere_De_Arta()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Opera", DbType="Int NOT NULL")]
		public int ID_Opera
		{
			get
			{
				return this._ID_Opera;
			}
			set
			{
				if ((this._ID_Opera != value))
				{
					this._ID_Opera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Comenzi", DbType="Int NOT NULL")]
		public int ID_Comenzi
		{
			get
			{
				return this._ID_Comenzi;
			}
			set
			{
				if ((this._ID_Comenzi != value))
				{
					this._ID_Comenzi = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departamente")]
	public partial class Departamente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Departament;
		
		private string _Nume_Departament;
		
		private EntitySet<Functii> _Functiis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DepartamentChanging(int value);
    partial void OnID_DepartamentChanged();
    partial void OnNume_DepartamentChanging(string value);
    partial void OnNume_DepartamentChanged();
    #endregion
		
		public Departamente()
		{
			this._Functiis = new EntitySet<Functii>(new Action<Functii>(this.attach_Functiis), new Action<Functii>(this.detach_Functiis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Departament", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Departament
		{
			get
			{
				return this._ID_Departament;
			}
			set
			{
				if ((this._ID_Departament != value))
				{
					this.OnID_DepartamentChanging(value);
					this.SendPropertyChanging();
					this._ID_Departament = value;
					this.SendPropertyChanged("ID_Departament");
					this.OnID_DepartamentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume_Departament", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Nume_Departament
		{
			get
			{
				return this._Nume_Departament;
			}
			set
			{
				if ((this._Nume_Departament != value))
				{
					this.OnNume_DepartamentChanging(value);
					this.SendPropertyChanging();
					this._Nume_Departament = value;
					this.SendPropertyChanged("Nume_Departament");
					this.OnNume_DepartamentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamente_Functii", Storage="_Functiis", ThisKey="ID_Departament", OtherKey="ID_Departatemt")]
		public EntitySet<Functii> Functiis
		{
			get
			{
				return this._Functiis;
			}
			set
			{
				this._Functiis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Functiis(Functii entity)
		{
			this.SendPropertyChanging();
			entity.Departamente = this;
		}
		
		private void detach_Functiis(Functii entity)
		{
			this.SendPropertyChanging();
			entity.Departamente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Depozit")]
	public partial class Depozit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Depozit;
		
		private string _Adresa;
		
		private string _Localitate;
		
		private int _Cod_Postal;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DepozitChanging(int value);
    partial void OnID_DepozitChanged();
    partial void OnAdresaChanging(string value);
    partial void OnAdresaChanged();
    partial void OnLocalitateChanging(string value);
    partial void OnLocalitateChanged();
    partial void OnCod_PostalChanging(int value);
    partial void OnCod_PostalChanged();
    #endregion
		
		public Depozit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Depozit", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Depozit
		{
			get
			{
				return this._ID_Depozit;
			}
			set
			{
				if ((this._ID_Depozit != value))
				{
					this.OnID_DepozitChanging(value);
					this.SendPropertyChanging();
					this._ID_Depozit = value;
					this.SendPropertyChanged("ID_Depozit");
					this.OnID_DepozitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresa", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Adresa
		{
			get
			{
				return this._Adresa;
			}
			set
			{
				if ((this._Adresa != value))
				{
					this.OnAdresaChanging(value);
					this.SendPropertyChanging();
					this._Adresa = value;
					this.SendPropertyChanged("Adresa");
					this.OnAdresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Localitate", DbType="NChar(40) NOT NULL", CanBeNull=false)]
		public string Localitate
		{
			get
			{
				return this._Localitate;
			}
			set
			{
				if ((this._Localitate != value))
				{
					this.OnLocalitateChanging(value);
					this.SendPropertyChanging();
					this._Localitate = value;
					this.SendPropertyChanged("Localitate");
					this.OnLocalitateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Postal", DbType="Int NOT NULL")]
		public int Cod_Postal
		{
			get
			{
				return this._Cod_Postal;
			}
			set
			{
				if ((this._Cod_Postal != value))
				{
					this.OnCod_PostalChanging(value);
					this.SendPropertyChanging();
					this._Cod_Postal = value;
					this.SendPropertyChanged("Cod_Postal");
					this.OnCod_PostalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Depozite_Opere")]
	public partial class Depozite_Opere
	{
		
		private int _ID_Depozit;
		
		private int _ID_Opera;
		
		private int _Numar;
		
		public Depozite_Opere()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Depozit", DbType="Int NOT NULL")]
		public int ID_Depozit
		{
			get
			{
				return this._ID_Depozit;
			}
			set
			{
				if ((this._ID_Depozit != value))
				{
					this._ID_Depozit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Opera", DbType="Int NOT NULL")]
		public int ID_Opera
		{
			get
			{
				return this._ID_Opera;
			}
			set
			{
				if ((this._ID_Opera != value))
				{
					this._ID_Opera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numar", DbType="Int NOT NULL")]
		public int Numar
		{
			get
			{
				return this._Numar;
			}
			set
			{
				if ((this._Numar != value))
				{
					this._Numar = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Expozitie")]
	public partial class Expozitie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Expozitie;
		
		private int _ID_Galerie;
		
		private string _Nume_Expozitie;
		
		private System.DateTime _Data_Inceput;
		
		private System.DateTime _Data_Sfarsit;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ExpozitieChanging(int value);
    partial void OnID_ExpozitieChanged();
    partial void OnID_GalerieChanging(int value);
    partial void OnID_GalerieChanged();
    partial void OnNume_ExpozitieChanging(string value);
    partial void OnNume_ExpozitieChanged();
    partial void OnData_InceputChanging(System.DateTime value);
    partial void OnData_InceputChanged();
    partial void OnData_SfarsitChanging(System.DateTime value);
    partial void OnData_SfarsitChanged();
    #endregion
		
		public Expozitie()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Expozitie", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Expozitie
		{
			get
			{
				return this._ID_Expozitie;
			}
			set
			{
				if ((this._ID_Expozitie != value))
				{
					this.OnID_ExpozitieChanging(value);
					this.SendPropertyChanging();
					this._ID_Expozitie = value;
					this.SendPropertyChanged("ID_Expozitie");
					this.OnID_ExpozitieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Galerie", DbType="Int NOT NULL")]
		public int ID_Galerie
		{
			get
			{
				return this._ID_Galerie;
			}
			set
			{
				if ((this._ID_Galerie != value))
				{
					this.OnID_GalerieChanging(value);
					this.SendPropertyChanging();
					this._ID_Galerie = value;
					this.SendPropertyChanged("ID_Galerie");
					this.OnID_GalerieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume_Expozitie", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Nume_Expozitie
		{
			get
			{
				return this._Nume_Expozitie;
			}
			set
			{
				if ((this._Nume_Expozitie != value))
				{
					this.OnNume_ExpozitieChanging(value);
					this.SendPropertyChanging();
					this._Nume_Expozitie = value;
					this.SendPropertyChanged("Nume_Expozitie");
					this.OnNume_ExpozitieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_Inceput", DbType="Date NOT NULL")]
		public System.DateTime Data_Inceput
		{
			get
			{
				return this._Data_Inceput;
			}
			set
			{
				if ((this._Data_Inceput != value))
				{
					this.OnData_InceputChanging(value);
					this.SendPropertyChanging();
					this._Data_Inceput = value;
					this.SendPropertyChanged("Data_Inceput");
					this.OnData_InceputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_Sfarsit", DbType="Date NOT NULL")]
		public System.DateTime Data_Sfarsit
		{
			get
			{
				return this._Data_Sfarsit;
			}
			set
			{
				if ((this._Data_Sfarsit != value))
				{
					this.OnData_SfarsitChanging(value);
					this.SendPropertyChanging();
					this._Data_Sfarsit = value;
					this.SendPropertyChanged("Data_Sfarsit");
					this.OnData_SfarsitChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Functii")]
	public partial class Functii : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Functie;
		
		private int _ID_Departatemt;
		
		private string _Denumire;
		
		private EntityRef<Departamente> _Departamente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_FunctieChanging(int value);
    partial void OnID_FunctieChanged();
    partial void OnID_DepartatemtChanging(int value);
    partial void OnID_DepartatemtChanged();
    partial void OnDenumireChanging(string value);
    partial void OnDenumireChanged();
    #endregion
		
		public Functii()
		{
			this._Departamente = default(EntityRef<Departamente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Functie", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Functie
		{
			get
			{
				return this._ID_Functie;
			}
			set
			{
				if ((this._ID_Functie != value))
				{
					this.OnID_FunctieChanging(value);
					this.SendPropertyChanging();
					this._ID_Functie = value;
					this.SendPropertyChanged("ID_Functie");
					this.OnID_FunctieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Departatemt", DbType="Int NOT NULL")]
		public int ID_Departatemt
		{
			get
			{
				return this._ID_Departatemt;
			}
			set
			{
				if ((this._ID_Departatemt != value))
				{
					if (this._Departamente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DepartatemtChanging(value);
					this.SendPropertyChanging();
					this._ID_Departatemt = value;
					this.SendPropertyChanged("ID_Departatemt");
					this.OnID_DepartatemtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Denumire", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Denumire
		{
			get
			{
				return this._Denumire;
			}
			set
			{
				if ((this._Denumire != value))
				{
					this.OnDenumireChanging(value);
					this.SendPropertyChanging();
					this._Denumire = value;
					this.SendPropertyChanged("Denumire");
					this.OnDenumireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamente_Functii", Storage="_Departamente", ThisKey="ID_Departatemt", OtherKey="ID_Departament", IsForeignKey=true)]
		public Departamente Departamente
		{
			get
			{
				return this._Departamente.Entity;
			}
			set
			{
				Departamente previousValue = this._Departamente.Entity;
				if (((previousValue != value) 
							|| (this._Departamente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Departamente.Entity = null;
						previousValue.Functiis.Remove(this);
					}
					this._Departamente.Entity = value;
					if ((value != null))
					{
						value.Functiis.Add(this);
						this._ID_Departatemt = value.ID_Departament;
					}
					else
					{
						this._ID_Departatemt = default(int);
					}
					this.SendPropertyChanged("Departamente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Expozitii_Opere_De_Arta")]
	public partial class Expozitii_Opere_De_Arta
	{
		
		private int _ID_Expozitie;
		
		private int _ID_Opera;
		
		public Expozitii_Opere_De_Arta()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Expozitie", DbType="Int NOT NULL")]
		public int ID_Expozitie
		{
			get
			{
				return this._ID_Expozitie;
			}
			set
			{
				if ((this._ID_Expozitie != value))
				{
					this._ID_Expozitie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Opera", DbType="Int NOT NULL")]
		public int ID_Opera
		{
			get
			{
				return this._ID_Opera;
			}
			set
			{
				if ((this._ID_Opera != value))
				{
					this._ID_Opera = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Functii_Angajati")]
	public partial class Functii_Angajati
	{
		
		private int _ID_Functie;
		
		private int _ID_Angajat;
		
		private System.DateTime _Data_Inceput;
		
		private System.Nullable<System.DateTime> _Data_Sfarsit;
		
		public Functii_Angajati()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Functie", DbType="Int NOT NULL")]
		public int ID_Functie
		{
			get
			{
				return this._ID_Functie;
			}
			set
			{
				if ((this._ID_Functie != value))
				{
					this._ID_Functie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Angajat", DbType="Int NOT NULL")]
		public int ID_Angajat
		{
			get
			{
				return this._ID_Angajat;
			}
			set
			{
				if ((this._ID_Angajat != value))
				{
					this._ID_Angajat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_Inceput", DbType="Date NOT NULL")]
		public System.DateTime Data_Inceput
		{
			get
			{
				return this._Data_Inceput;
			}
			set
			{
				if ((this._Data_Inceput != value))
				{
					this._Data_Inceput = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_Sfarsit", DbType="Date")]
		public System.Nullable<System.DateTime> Data_Sfarsit
		{
			get
			{
				return this._Data_Sfarsit;
			}
			set
			{
				if ((this._Data_Sfarsit != value))
				{
					this._Data_Sfarsit = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Galerii_Departamente")]
	public partial class Galerii_Departamente
	{
		
		private int _ID_Departament;
		
		private int _ID_Galerie;
		
		public Galerii_Departamente()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Departament", DbType="Int NOT NULL")]
		public int ID_Departament
		{
			get
			{
				return this._ID_Departament;
			}
			set
			{
				if ((this._ID_Departament != value))
				{
					this._ID_Departament = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Galerie", DbType="Int NOT NULL")]
		public int ID_Galerie
		{
			get
			{
				return this._ID_Galerie;
			}
			set
			{
				if ((this._ID_Galerie != value))
				{
					this._ID_Galerie = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Opere_De_Arta")]
	public partial class Opere_De_Arta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Opera;
		
		private int _ID_Autor;
		
		private string _Nume;
		
		private string _An;
		
		private double _Pret_RON_;
		
		private string _Detalii;
		
		private string _ImageURL;
		
		private EntityRef<Autor> _Autor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_OperaChanging(int value);
    partial void OnID_OperaChanged();
    partial void OnID_AutorChanging(int value);
    partial void OnID_AutorChanged();
    partial void OnNumeChanging(string value);
    partial void OnNumeChanged();
    partial void OnAnChanging(string value);
    partial void OnAnChanged();
    partial void OnPret_RON_Changing(double value);
    partial void OnPret_RON_Changed();
    partial void OnDetaliiChanging(string value);
    partial void OnDetaliiChanged();
    partial void OnImageURLChanging(string value);
    partial void OnImageURLChanged();
    #endregion
		
		public Opere_De_Arta()
		{
			this._Autor = default(EntityRef<Autor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Opera", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Opera
		{
			get
			{
				return this._ID_Opera;
			}
			set
			{
				if ((this._ID_Opera != value))
				{
					this.OnID_OperaChanging(value);
					this.SendPropertyChanging();
					this._ID_Opera = value;
					this.SendPropertyChanged("ID_Opera");
					this.OnID_OperaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Autor", DbType="Int NOT NULL")]
		public int ID_Autor
		{
			get
			{
				return this._ID_Autor;
			}
			set
			{
				if ((this._ID_Autor != value))
				{
					if (this._Autor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_AutorChanging(value);
					this.SendPropertyChanging();
					this._ID_Autor = value;
					this.SendPropertyChanged("ID_Autor");
					this.OnID_AutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this.OnNumeChanging(value);
					this.SendPropertyChanging();
					this._Nume = value;
					this.SendPropertyChanged("Nume");
					this.OnNumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_An", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string An
		{
			get
			{
				return this._An;
			}
			set
			{
				if ((this._An != value))
				{
					this.OnAnChanging(value);
					this.SendPropertyChanging();
					this._An = value;
					this.SendPropertyChanged("An");
					this.OnAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Pret(RON)]", Storage="_Pret_RON_", DbType="Float NOT NULL")]
		public double Pret_RON_
		{
			get
			{
				return this._Pret_RON_;
			}
			set
			{
				if ((this._Pret_RON_ != value))
				{
					this.OnPret_RON_Changing(value);
					this.SendPropertyChanging();
					this._Pret_RON_ = value;
					this.SendPropertyChanged("Pret_RON_");
					this.OnPret_RON_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalii", DbType="NChar(500) NOT NULL", CanBeNull=false)]
		public string Detalii
		{
			get
			{
				return this._Detalii;
			}
			set
			{
				if ((this._Detalii != value))
				{
					this.OnDetaliiChanging(value);
					this.SendPropertyChanging();
					this._Detalii = value;
					this.SendPropertyChanged("Detalii");
					this.OnDetaliiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageURL", DbType="NChar(150)")]
		public string ImageURL
		{
			get
			{
				return this._ImageURL;
			}
			set
			{
				if ((this._ImageURL != value))
				{
					this.OnImageURLChanging(value);
					this.SendPropertyChanging();
					this._ImageURL = value;
					this.SendPropertyChanged("ImageURL");
					this.OnImageURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Autor_Opere_De_Arta", Storage="_Autor", ThisKey="ID_Autor", OtherKey="ID_Autor", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Autor Autor
		{
			get
			{
				return this._Autor.Entity;
			}
			set
			{
				Autor previousValue = this._Autor.Entity;
				if (((previousValue != value) 
							|| (this._Autor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Autor.Entity = null;
						previousValue.Opere_De_Artas.Remove(this);
					}
					this._Autor.Entity = value;
					if ((value != null))
					{
						value.Opere_De_Artas.Add(this);
						this._ID_Autor = value.ID_Autor;
					}
					else
					{
						this._ID_Autor = default(int);
					}
					this.SendPropertyChanged("Autor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Username;
		
		private string _Password;
		
		private int _UserType;
		
		private string _CNP;
		
		private EntitySet<Comenzi> _Comenzis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnUserTypeChanging(int value);
    partial void OnUserTypeChanged();
    partial void OnCNPChanging(string value);
    partial void OnCNPChanged();
    #endregion
		
		public User()
		{
			this._Comenzis = new EntitySet<Comenzi>(new Action<Comenzi>(this.attach_Comenzis), new Action<Comenzi>(this.detach_Comenzis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="Int NOT NULL")]
		public int UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this.OnUserTypeChanging(value);
					this.SendPropertyChanging();
					this._UserType = value;
					this.SendPropertyChanged("UserType");
					this.OnUserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNP", DbType="Char(13)")]
		public string CNP
		{
			get
			{
				return this._CNP;
			}
			set
			{
				if ((this._CNP != value))
				{
					this.OnCNPChanging(value);
					this.SendPropertyChanging();
					this._CNP = value;
					this.SendPropertyChanged("CNP");
					this.OnCNPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Comenzi", Storage="_Comenzis", ThisKey="ID", OtherKey="ID_User")]
		public EntitySet<Comenzi> Comenzis
		{
			get
			{
				return this._Comenzis;
			}
			set
			{
				this._Comenzis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comenzis(Comenzi entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Comenzis(Comenzi entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
}
#pragma warning restore 1591
