//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analizatori.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Analizatori.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ANALIZATORUL_ACUSTICO {
            get {
                object obj = ResourceManager.GetObject("ANALIZATORUL_ACUSTICO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Analizatorul_acustico_vestivular {
            get {
                object obj = ResourceManager.GetObject("Analizatorul_acustico_vestivular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ANALIZATORUL_CUTANAT {
            get {
                object obj = ResourceManager.GetObject("ANALIZATORUL_CUTANAT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Analizatorul_cutanat1 {
            get {
                object obj = ResourceManager.GetObject("Analizatorul_cutanat1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Analizatorul_vizual {
            get {
                object obj = ResourceManager.GetObject("Analizatorul_vizual", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Analizatorul_vizual1 {
            get {
                object obj = ResourceManager.GetObject("Analizatorul_vizual1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img1 {
            get {
                object obj = ResourceManager.GetObject("img1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img2 {
            get {
                object obj = ResourceManager.GetObject("img2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img3 {
            get {
                object obj = ResourceManager.GetObject("img3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img4 {
            get {
                object obj = ResourceManager.GetObject("img4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img5 {
            get {
                object obj = ResourceManager.GetObject("img5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Introducere {
            get {
                object obj = ResourceManager.GetObject("Introducere", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PATOLOGIILE {
            get {
                object obj = ResourceManager.GetObject("PATOLOGIILE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unde se află ciocanul, nicovala și scărița?
        ///3
        ///în urechea externă
        ///în urechea medie
        ///în urechea internă
        ///în urechea medie
        ///
        ///Urechea internă este formată din:
        ///4
        ///labirintul osos
        ///ciocan
        ///nicovală
        ///scăriță
        ///labirintul osos
        ///
        ///Labirintul osos este alcătuit din:
        ///3
        ///ciocan
        ///melc osos
        ///trei canale semicirculare,vestibul osos și melcul osos
        ///trei canale semicirculare,vestibul osos și melcul osos
        ///
        ///Cum se mai numește melcul osos?
        ///4
        ///scăriță
        ///cohlee
        ///ciocan
        ///endolimfă
        ///cohlee
        ///
        ///De ce este reprezentat segmentu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quiz_analizatorul_acustico_vestibular {
            get {
                return ResourceManager.GetString("quiz_analizatorul_acustico_vestibular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din ce straturi este formată pielea?
        ///4
        ///epiderm
        ///derm
        ///epiderm, derm, hipoderm
        ///țesut conjunctiv
        ///epiderm, derm, hipoderm
        ///Unde sunt situați corpusculii Krause?
        ///3
        ///în derm
        ///în hipoderm
        ///în epiderm
        ///în derm
        ///Unde se află segmentul central?
        ///4
        ///în girusul postcentral din lobul parietal – ariile somestezice
        ///în talamus
        ///în măduva spinării
        ///în bulbul rahidian
        ///în girusul postcentral din lobul parietal – ariile somestezice
        ///Cum mai este denumită sensibilitatea tactilă fină?
        ///3
        ///protopatică
        ///epicritică
        ///tegumen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quiz_analizatorul_cutanat {
            get {
                return ResourceManager.GetString("quiz_analizatorul_cutanat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din câte tunici este alcătuit globul ocular?
        ///4
        ///două tunici
        ///cinci tunici
        ///trei tunici 
        ///patru tunici
        ///trei tunici
        ///Ce prezintă tunica externă?
        ///4
        ///sclerotică
        ///cornee
        ///coroidă
        ///sclerotică și cornee
        ///sclerotică și cornee
        ///Câte porțiuni are tunica medie și care sunt?
        ///3
        ///două: coroida, corpul ciliar
        ///trei: coroida, corpul ciliar, irisul
        ///trei: coroida, corpul ciliar, sclerotica
        ///trei: coroida, corpul ciliar, irisul
        ///Care sunt zonele importante ale tunicii interne?
        ///3
        ///macula lutea și pata oarbă
        ///irisul și co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quiz_analizatorul_vizual {
            get {
                return ResourceManager.GetString("quiz_analizatorul_vizual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce este herpesul?
        ///3
        ///boală a pielii și a mucoaselor
        ///boală a analizatorului vizual
        ///boală a analizatorului vestibular
        ///boală a pielii și a mucoaselor
        ///Cauzele producerii herpesului sunt:
        ///4
        ///lovituri
        ///diabet
        ///virale
        ///intoxicații
        ///virale
        ///Cum se mai numește glaucomul?
        ///3
        ///pată neagră
        ///pată albă
        ///apa neagră
        ///apa neagră
        ///Cauzele producerii conjunctivitei sunt:
        ///4
        ///infecție virală
        ///lovituri
        ///diabet
        ///vârsta înaintată
        ///infecție virală
        ///Cauzele producerii otitei sunt:
        ///3
        ///infecție virală
        ///lovituri
        ///micotice, bact [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quiz_patologii {
            get {
                return ResourceManager.GetString("quiz_patologii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Șțiați_că {
            get {
                object obj = ResourceManager.GetObject("Șțiați_că", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
